SHELL := /usr/bin/env bash

all: \
	example/proto \
	eslint

include tools/semantic-release/rules.mk
include tools/eslint/rules.mk

.PHONY: example/proto
example/proto:
	@make -C $@

.PHONY: $(eslint)
eslint: $(eslint)
	$(info [$@] linting typescript files...)
	$(eslint) --config $(eslint_cwd)/.eslintrc.js --quiet "example/proto/gen/typescript/**/*.ts"
