name: release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: '1.23'

      - name: Make
        run: make

      - name: Create release
        id: release
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true

      - name: Run GoReleaser
        run: make go-releaser snapshot=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
