name: review

on:
  pull_request:
    branches:
      - "*"

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: 1.19

      - name: Make
        run: make

      - name: Dry-run release
        id: release
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
          dry: true

      - name: Dry-run GoReleaser
        run: make go-releaser snapshot=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
